apiVersion: v1
kind: Pod
metadata:
  name: hc-vault-pod-1
  labels:
    app: hc-vault-1
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-inject-status: 'update'
    vault.hashicorp.com/role: "app"
    vault.hashicorp.com/agent-inject-secret-secret-credentials.txt: "secret/data/home/app"
    vault.hashicorp.com/agent-inject-template-secret-credentials.txt: |
          {{- with secret "secret/data/home/app" -}}
          db.user={{ .Data.data.db_user }} 
          {{- end -}}
spec:
  serviceAccountName: internal-app
  containers:
    - name: hc-vault-container-1
      image: pylagg/first_repo:app_v1.3
      imagePullPolicy: Always
      ports:
        - containerPort: 8090
          name: "app-port-1"